version: '1'
services: 
  jupyter_lab:
    container_name: amanda-jupyter
    build:
      context: .
      dockerfile: jupyterGPU.Dockerfile
    ports: 
      - "60701:8888"
    environment: 
      - JUPYTER_ENABLE_LAB=yes
      - NVIDIA_VISIBLE_DEVICES=3
    volumes: 
      - ./code:/traducao-amanda-container/code
networks:
  default:
    external:
      name: amanda-network
    
      
