version: '1'
services: 
  jupyter_lab:
    container_name: amanda-jupyter
    build:
      context: .
      dockerfile: jupyter.Dockerfile
    ports: 
      - "60702:8888"
    environment: 
      - JUPYTER_ENABLE_LAB=yes
    volumes: 
      - ./code:/traducao-amanda-container/code
    
      
