version: '1'
services: 
  jupyter_lab:
    container_name: jupyter_lab
    build:
      context: .
      dockerfile: jupyter.Dockerfile
    ports: 
      - "60701:8888"
    environment: 
      - JUPYTER_ENABLE_LAB=yes
      - PIP_NO_CACHE_DIR=1
    volumes: 
      - ./code:/traducao-amanda-container/code-container
      
